### ISSUE TITLE
`clusterInstanceHostPattern` is required with aurora db

### ISSUE THREAD

**Issue by Howu48** [awslabs/aws-mysql-jdbc#190]
**Describe the issue**
`clusterInstanceHostPattern` is required when using `Aurora` + `software.aws.rds.jdbc.mysql.Driver`
(`acceptAwsProtocolOnly` is also not working for me)
```
java.sql.SQLException: The clusterInstanceHostPattern configuration property is required when an IP address or custom domain is used to connect to a cluster that provides topology information. If you would instead like to connect without failover functionality, set the enableClusterAwareFailover configuration property to false.
```

`Instance` + `software.aws.rds.jdbc.mysql.Driver` or `RDS` + `software.aws.rds.jdbc.mysql.Driver` is working fine

**Driver Version?** 
1.0.0
**Java Version?**
8
**OS Version?**
Ubuntu18
**MySQL Version?**
5.7
**To Reproduce**
Steps to reproduce the behaviour:
- build.gradle
```
    implementation 'software.aws.rds:aws-mysql-jdbc:1.0.0'
```
- application.yml
```
test-db:
    pool-name: test-db
    driverClassName: software.aws.rds.jdbc.mysql.Driver
    jdbc-url: jdbc:mysql:aws://localhost:25306/test-db
```
- `localhost:25306` is connected with `Aurora DB` through ssh tunnel
- HikariCP Datasource

**Expected behaviour**

**Logs**

**Comment by sergiyvamz** [comment]
Hello @Howu48,

Thank you for giving the AWS JDBC Driver for MySQL a try!

The driver requires `clusterInstanceHostPattern` parameter when connection string doesn't provide enough details about DB cluster domain name. If Aurora cluster endpoint is used in connection string, the driver recognizes standard Aurora domain name and can re-build a proper Aurora instance endpoint name when needed. In other cases, when connection string uses IP address, a custom domain name or localhost, the driver needs a hint how to build a proper domain name for a DB instance.

In your configuration `localhost:25306` is rerouted to Aurora DB cluster via SSH tunnel. It's not clear from your description whether the tunnel can also handle Aurora DB instance endpoints. If the tunnel can handle local subdomains like `*.localhost`, the following parameter to connection string can be used:

`clusterInstanceHostPattern=?.localhost`

You also need to configure your SSH tunnel to handle localhost subdomains on the same port and to route them to corresponding Aurora DB instance endpoints.

You can find more details about `clusterInstanceHostPattern` parameter at 
https://github.com/awslabs/aws-mysql-jdbc#failover-parameters

**Comment by Howu48** [comment]
@sergiyvamz Thank you for your answer.

I'm not sure what `the tunnel can also handle Aurora DB instance endpoints` means, but `clusterInstanceHostPattern=?.localhost` is working fine.

My question is, why only `Aurora cluster` is required that parameter? 🤔 
As I mentioned on description, If I just change the endpoint to `RDS instance` (MySQL Community, via SSH tunnel too) it works well without `clusterInstanceHostPattern` parameter. 

- `localhost:25306` ssh tunneling to `Aurora cluster`: need `clusterInstanceHostPattern=?.localhost`
- `localhost:25306` ssh tunneling to `RDS instance` : no need any optional paramater

Both of `Aurora cluster` and `RDS instance` have default host pattern
(like `db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:3306` / `jdbc:mysql:aws://instance-1.XYZ.us-east-2.rds.amazonaws.com:3306`)

**Comment by sergiyv-bitquill** [comment]
Hello @Howu48,

Sorry I wasn't clear about tunnel. Your tunnel needs to properly route driver requests to corresponding DB instances. Assuming your Aurora DB cluster has 3 instances (instance-1, instance-2, instance-3) and you use `clusterInstanceHostPattern=?.localhost`, your tunnel needs to support the following routing:

`instance-1.localhost:25306` -> `instance-1.<account-id>.<region>.rds.amazonaws.com:3306`
`instance-2.localhost:25306` -> `instance-2.<account-id>.<region>.rds.amazonaws.com:3306`
`instance-3.localhost:25306` -> `instance-3.<account-id>.<region>.rds.amazonaws.com:3306`

In case of failover, the driver gets an updated DB cluster topology and tries to connect to a new writer by using an instance  endpoint (`instance-1.localhost:25306`, `instance-2.localhost:25306`, `instance-3.localhost:25306`). It's important to make sure that tunnel can handle routing mentioned above.

The difference between `Aurora cluster` and `RDS instance` is about supporting failover. Aurora cluster supports failover while RDS instance doesn't. The driver recognizes whether database is Aurora cluster and engages failover support if needed.  For Aurora clusters, depending on what URL is used in a connection string, the drive may require additional details on how to construct a full instance endpoint. That's why `clusterInstanceHostPattern` parameter may be required in some cases. You can find more details at https://github.com/awslabs/aws-mysql-jdbc#connection-url-descriptions

**Comment by sergiyvamz** [comment]
Hello @Howu48,

Sorry I wasn't clear about tunnel. Your tunnel needs to properly route driver requests to corresponding DB instances. Assuming your Aurora DB cluster has 3 instances (instance-1, instance-2, instance-3) and you use `clusterInstanceHostPattern=?.localhost`, your tunnel needs to support the following routing:

`instance-1.localhost:25306` -> `instance-1.<account-id>.<region>.rds.amazonaws.com:3306`
`instance-2.localhost:25306` -> `instance-2.<account-id>.<region>.rds.amazonaws.com:3306`
`instance-3.localhost:25306` -> `instance-3.<account-id>.<region>.rds.amazonaws.com:3306`

In case of failover, the driver gets an updated DB cluster topology and tries to connect to a new writer by using an instance  endpoint (`instance-1.localhost:25306`, `instance-2.localhost:25306`, `instance-3.localhost:25306`). It's important to make sure that tunnel can handle routing mentioned above.

The difference between `Aurora cluster` and `RDS instance` is about supporting failover. Aurora cluster supports failover while RDS instance doesn't. The driver recognizes whether database is Aurora cluster and engages failover support if needed.  For Aurora clusters, depending on what URL is used in a connection string, the drive may require additional details on how to construct a full instance endpoint. That's why `clusterInstanceHostPattern` parameter may be required in some cases. You can find more details at https://github.com/awslabs/aws-mysql-jdbc#connection-url-descriptions

**Comment by Howu48** [comment]
@sergiyvamz Thank you for your answer again!

About my tunnel, It actually looks like
`(My local pc) localhost:25306` -> `(Aurora cluster) instance-1.<account-id>.<region>.rds.amazonaws.com:3306`.
Anyway tunnel & `clusterInstanceHostPattern` is work just fine, so it is not the point 😃 

About failover, now I see what I was missing. 
I thought the driver makes regular JDBC connection if connection string is set like `jdbc:mysql:aws://localhost:3306`.
But truth, driver makes failover support connection because the endpoint is `Aurora cluster`, so driver require `clusterInstanceHostPattern` for replace cluster domain url when failover occurs.
Did I get it right? If so, is there any way to avoid using `clusterInstanceHostPattern`?

In my team's case, we have to use SSH tunneling for DB connection in local environment(because of internal firewall policy) but in dev or prd environment, each instance directly connected to DB endpoint.
So connection string is actually like this:
```
test-db:
    pool-name: test-db
    driverClassName: software.aws.rds.jdbc.mysql.Driver
    jdbc-url: jdbc:mysql:aws://${DB_ENDPOINT}/test-db
```
`${DB_ENDPOINT}` is replaced each instance's environment variable(only local pc use `localhost`).
I think if I add `clusterInstanceHostPattern=?.localhost`, failover dose not work properly.
(I'm thinking about using `clusterInstanceHostPattern=?.*`, but not sure... 🤔)

Best option for me is the driver decides connection type by given connection string, not DB instance type (It's better if user can toggle this)

**Comment by sergiyvamz** [comment]
Hello @Howu48,

If you need to avoid using `clusterInstanceHostPattern` parameter you may either 
1) use Aurora endpoints for Aurora clusters, or 
2) use simple RDS MySQL database (that isn't a cluster and doesn't support failover), or
3) disable failover support by AWS driver 

Since you use a tunnel and `localhost` just in local development then you may consider to go with option 3). In this case
you are not be able to develop and test failover-related scenarios in your application but it helps you to keep your configuration simple. You can add `enableClusterAwareFailover=false` to your connection string for local configuration. `clusterInstanceHostPattern` parameter isn't necessary in this case.

**Comment by Howu48** [comment]
Okay... I have to separate configuration profile eventually, but `enableClusterAwareFailover` parameter seems more appropriate. Thanks for your help.

It would be nice if you consider to add an option I commented (`Driver decides connection behavior by given URL type`) 😃
