### ISSUE TITLE
Aurora - Support for Writer & Reader cluster in the jdbc URL

### ISSUE THREAD

**Issue by lijubsgit** [awslabs/aws-mysql-jdbc#202]
When the writer & reader cluster URL is provided, the driver failed with a "Communications link failure" error message. the JDBC url is of format - ```jdbc:mysql:aws://<Write Cluster URL>:<port>;<Read cluster URL>:<PORT>/<DB name>?useSSL=true&requireSSL=true&sslrootcert=rds-combined-ca-bundle.pem``` . Is the case the driver accepts one type of URL and the client needs to maintain a separate write & read connection pool? MariaDB driver with aurora prefix 
is used to supporting this format and balances connections between write & read replicas. What is the suggested approach to implementing the same in the aws JDBC driver?

BTW, the same url works if the writer cluster url or the reader cludetr url is provided alone.

**Comment by bobfields** [comment]
Also - if the writer instance is used and we have Spring @Transactional(readOnly=true), the SQL should be routed to the readonly replica database. Just like with the mariadb driver (v2.7.5).

**Comment by sergiyvamz** [comment]
Hello @lijubsgit 

Unfortunately AWS JDBC Driver for MySQL, while using "jadbc:mysql:aws://" protocol, doesn't support read/write split. The driver accepts just a single URL in a connection string.

Separate connection pools for read and write traffic could be a possible solution.

Read/write split functionality is currently being looked into. We cannot confirm exact timelines for when this feature will be added, but we are investigating. Since we work in the open, we can update this discussion for visibility when implementation starts.

**Comment by csyperski** [comment]
I came here to research this as well, we are currently using mysql rds with jdbc:mysql:replication to handle the exact issue mentioned with Spring's @transactional(readOnly=true) to route to read-only nodes instead of write nodes.  We are attempting to switch to aurora, but seeing the Maria driver is deprecated and this driver doesn't handle the routing via the connection being set to readOnly is a bit of a bummer.  

So am I understanding this right then that this driver doesn't really utilitze the RO nodes at all when using the "default" (Cluster Endpoint) connection url of:
jdbc:mysql:aws://db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:3306

I was hoping that when using this URL, non read-only connections would go to the writer and read-only connections would go to a read-only replica either using random or round-robin by default.  Am I misunderstanding?  

I'd also recommend to document this in the documentation a bit more, the documentation seems to focus on the speed of fail over, but seems a bit lite on this as I think it is a pretty common pattern, especially with spring/spring boot applicaitons.   

Our full jdbc string take the following form currently (for context):
jdbc:mysql:replication://rw.domain.com:3306,ro.domain.com:3306/xxxxx?autoReconnect=true&serverTimezone=UTC&&allowSlavesDownConnections=true&readFromMasterWhenNoSlaves=true&loadBalanceBlacklistTimeout=5000

**Comment by karenc-bq** [comment]
Hi @csyperski, your understanding is correct. We are currently working on read/write split support, we will let you know once the feature has been implemented. We appreciate your patience.
Thank you for your suggestion on the documentation, we will improve our documentation in future releases.

**Comment by hsuamz** [comment]
Closing this issue as the read/write splitting feature is currently being worked on. Discussions regarding the feature can be carried over to here: https://github.com/awslabs/aws-mysql-jdbc/discussions/192.
