### ISSUE TITLE
Using read-only endpoint, but all queries are going to the writer instance after a failover

### ISSUE THREAD

**Issue by bjlkak** [awslabs/aws-mysql-jdbc#204]
**Describe the issue**
Using read-only endpoint, but all queries are going to the writer instance after a failover. I've also tried injecting disk congestion query to the new promoted primary, but it won't reroute the queries to read replica.

**Driver Version?**
1.0.0

**Java Version?**
openjdk 11.0.11

**OS Version?**
macOS 11.4

**MySQL Version?**
5.7.mysql_aurora.2.07.2

**To Reproduce**
In a AWS RDS cluster have two instances, one writer and and one reader. Use read-only endpoint for jdbc url and start sending read request and perform a failover on writer instance.

**Expected behaviour**
Once failover finishes queries should balance out or move to new read replicas.

**Comment by sergiyvamz** [comment]
Hello @bjlkak 

Thank you for reaching out! By using read-only endpoint in a connection string, the driver opens an initial connection to a specified node. During failover the driver reconnects to a new elected writer. More details about driver logic during failover can be found at https://github.com/awslabs/aws-mysql-jdbc#connection-url-descriptions

If your application prefers a replica connection after failover, you may consider to use `setReadOnly(true)` on your connection object. This gives the driver a hint and allows to failover to a replica. 

Another possible solution is to use a Cluster Reader Endpoint (instead of an instance endpoint) in a connection string. 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html#Aurora.Endpoints.Reader

**Comment by bjlkak** [comment]
Hi thank you for the response. So I've tried setting setReadOnly to true, but it still seems like the connection is still going to primary after the failover. Do we need to create a new connection?

Also I am using cluster reader endpoint here NOT the instance endpoint and seeing this issue.

Thank you!

**Comment by sergiyvamz** [comment]
Hello @bjlkak 

You may consider to configure driver logs. That can help to troubleshoot the case. A cluster configuration with 2 nodes (1 writer + 1 reader) isn't typical. During failover process both nodes change their roles and both get unavailable for a short period of time (10-30s) so that may "confuse" the driver. In such case the driver may prioritize any available connection (including a writer connection) over user preferences.
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-debugging-profiling.html

**Comment by bjlkak** [comment]
Hi, so what I attached a log here. This time what I did was I connected to the reader and performed a failover on the reader, so that writer became to new reader. However, instead of going to the new reader, it still went to the writer.
[jdbc.log](https://github.com/awslabs/aws-mysql-jdbc/files/8665634/jdbc.log)

**Comment by bjlkak** [comment]
and this is the log where I had two readers and a writer. I was connected to the reader (cluster read-only endpoint) and performed a failover on the writer. But still switched over to the new promoted writer at the end.
[jdbc1.log](https://github.com/awslabs/aws-mysql-jdbc/files/8665670/jdbc1.log)

**Comment by bjlkak** [comment]
Hi @sergiyvamz 

Have you had a chance to take a look at the logs?

thanks 😄

**Comment by sergiyvamz** [comment]
Hi @bjlkak 

It seems that it might be an issue on the driver side. Logs say that the driver reconnects to a proper replica however I suspect that Hikari CP may not properly recognize a returned exception and force to close the connection. 

Do you use a solution mentioned in the driver documentation? 
https://github.com/awslabs/aws-mysql-jdbc#connection-pooling

Meanwhile we're continue working on the issue. I'll keep you posted. Thank you!

**Comment by bjlkak** [comment]
yes in the beginning of the log `Loading AwsHikariCpSqlExceptionOverride` that class is the exception is handled.

Thanks for keep looking into this!

**Comment by karenc-bq** [comment]
Hi @bjlkak, how are you checking the type of Aurora instance you are connected to? Do you use [isReadOnly](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#isReadOnly--) or do you query against a specific server variable?

**Comment by bjlkak** [comment]
Hi @karenc-bq I am using both I am doing `select @@innodb_read_only, @@aurora_server_id` to get the info

**Comment by albanf** [comment]
I've experienced similar issues, but I think this is because during the all read-only connections are re-routed to the new writer, which is the only one available for a moment.
Initial state: Instance-0: RW ; Instance-1: RO

First the replica is stopped: Instance-0: RW ; Instance-1: down
So all RO connections are re-rerouted to Instance-0.

Then the replica is promoted and the writer is stopped: Instance-0: down; Instance-1: RW
All connections, RW and RO are re-routed to Instance-1.

Then Instance-0 starts: Instance-0: RO; Instance-1: RW

All connections are ok, so they are not re-routed. The rebalancing could be handled in the pool, with a low enough idle timeout, or by setting a TTL for the active connections (I think Hikari has such a setting).
