### ISSUE TITLE
Create HikariDataSource with SecretId and REGION

### ISSUE THREAD

**Issue by goodidea-kp** [awslabs/aws-mysql-jdbc#346]
### Describe the issue

At this moment example has only gotten a connection from DriverManager. 

     final Properties properties = new Properties();
      // Enable the AWS Secrets Manager Plugin:
      properties.setProperty("connectionPluginFactories", AWSSecretsManagerPluginFactory.class.getName());
      
      // Set these properties so secrets can be retrieved:
      properties.setProperty("secretsManagerSecretId", SECRET_ID);
      properties.setProperty("secretsManagerRegion", REGION);

      // Try and make a connection:
      try (final Connection conn = DriverManager.getConnection(CONNECTION_STRING, properties);

It has low practical application from SpringBoot development. SpringBoot uses the HickaryDataSource approach. Can we have a configuration example AWSSecretsManagerPluginFactory+Secret_ID+REGION+HikariDataSource+SpringBoot?

### Links

https://github.com/awslabs/aws-mysql-jdbc#example

**Comment by abedali** [comment]
I was able to figure it out using several trials. Hope this helps

hikari.dataSourceProperties.secretsManagerSecretId=<secretId>
hikari.dataSourceProperties.secretsManagerRegion=<region>

**Comment by karenc-bq** [comment]
Hi @goodidea-kp, the example provided by @abedali should work.
Do you need more help configuring the Spring Boot application with the AWS Secrets Manager plugin?

**Comment by aaronchung-bitquill** [comment]
Hi @goodidea-kp 

We haven't heard back from you for some time, so we wanted to check back in again to see if you needed any more help? 

If not, since a solution has been provided, we will be closing this issue in the next days if we don't hear back from you. However, if you still need help after we have closed this ticket, please feel free to re-open this issue or create a new one. 

Thank you!
