### ISSUE TITLE
Support for HikariCP Connection pool - Question

### ISSUE THREAD

**Issue by narayananl23** [awslabs/aws-mysql-jdbc#61]
**Describe the issue**
Do you support HikariCP , we are using mysql with HikariCP https://github.com/brettwooldridge/HikariCP  and evaluating the Amazon Aurora MYSQL. 

**Driver Version?** 
0.1.0. 

**Java Version?**
Open JDK 11

**OS Version?**
NA

**MySQL Version?**
5.7

**To Reproduce**
NA

**Expected behaviour**
NA

**Logs**
Failed to load driver class software.aws.rds.jdbc.mysql.Driver in either of HikariConfig class loader or Thread context classloader

**Comment by hsuamz** [comment]
Hello @narayananl23,

Thanks for reaching out and thanks for evaluating Amazon Aurora MySQL. We wanted to clarify the driver name since there may be an issue with the naming as shared in your logs.

If you're using the `0.1.0` public preview release, the driver name was `software.aws.rds.jdbc.Driver`. We've changed the driver name on our mainline branch to distinguish better between our [AWS JDBC Driver for PostgreSQL](https://github.com/awslabs/aws-postgresql-jdbc).

Would you be able to specify the driver name as `software.aws.rds.jdbc.Driver` and see if that resolves your issue?

Thanks,

Matthew

**Comment by narayananl23** [comment]
@hsuamz 

That made some progress. Now I get this error..


![image](https://user-images.githubusercontent.com/3720723/116607601-0f261d80-a8e7-11eb-8a2f-67973d0826d0.png)

**Comment by narayananl23** [comment]
@hsuamz 

FYI 
For the same Amazon Aurora MYSQL server, everything works fine, if we use "com.mysql.cj.jdbc.Driver"  for DriverClassName

**Comment by hsuamz** [comment]
Thanks @narayananl23,

We believe this a known issue for some workflows and this has been recently fixed on our main branch. Since the driver is based on the MySQL community driver, the MySQL protocol is compatible. One thing to note is if you plan on using the community driver alongside the AWS driver, please refer to the configuration `acceptAwsProtocolOnly` on our README.

If you're able to build the driver on our main branch and use that, the issue should not be present anymore. We are working on scheduling an updated release based on our latest changes that are published on our main branch.

Please let us know if there is anything else we can help out with.

Thanks,

Matthew

**Comment by narayananl23** [comment]
@hsuamz 

It works now..   Thanks for the pointers. When it is scheduled for an updated release ?

Few tips others..

1) `software.aws.rds.jdbc.mysql.Driver.setAcceptAwsProtocolOnly(true); `

If we need to build and add to local maven. 
2) Once you built the project to add it to local repo.. 
```
mvn install:install-file \
   -Dfile=<path-to-file> \
   -DgroupId=<group-id> \
   -DartifactId=<artifact-id> \
   -Dversion=<version> \
   -Dpackaging=<packaging> \
   -DgeneratePom=true
```

e.g 
`mvn install:install-file -Dfile=/pathtofolder/aws-mysql-jdbc/build/libs/aws-mysql-jdbc-1.0.0.jar -DgroupId=software.aws.rds -DartifactId=aws-mysql-jdbc -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true`


3) Follow  [https://github.com/awslabs/aws-mysql-jdbc#driver-name] 
Change  "software.aws.rds.jdbc.Driver" to  "software.aws.rds.jdbc.mysql.Driver" 

4)
Make sure you have :aws in the connection param 

jdbc:mysql://XXXX.cluster-XXXXX.us-east-1.rds.amazonaws.com:3306/abc?serverTimezone=UTC
Vs 
jdbc:mysql:aws://XXXX.cluster-XXXXX.us-east-1.rds.amazonaws.com:3306/abc?serverTimezone=UTC
